apiVersion: v1
kind: ConfigMap
metadata:
  name: rooms-config
data:
  DATABASE_HOST: 'mysql'
  DATABASE_PORT: '3306'
  #DATABASE_USERNAME: 'minikube'
  #DATABASE_PASSWORD: 'minikube'
  DATABASE_SCHEMA: 'coches'
  CORS_ORIGIN: 'http://localhost:4200'
  RABBITMQ_HOST: 'rabbitmq'
  RABBITMQ_PORT: '5672'
  RABBITMQ_QUEUE: 'foo'
  RABBITMQ_VHOST: '/'
  MICRO_USERS_PROTOCOL: 'http'
  MICRO_USERS_HOST: 'users'
  MICRO_USERS_PORT: '3000'
  MICRO_USERS_GET_TOKEN_PATH: 'users/token'
  MICRO_USERS_CREATE_PATH: 'users/create'
  MICRO_USERS_FIND_BY_ID: 'users/'