apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
spec:
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
      - name: rooms
        image: coches/rooms
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: rooms-config
          - secretRef:
              name:  rooms-secret
            
